"""
Fronius API Client Module

This module provides a client for interacting with Fronius solar inverters.
It handles communication with the inverter's REST API to fetch real-time power data.

The Fronius inverter provides data about:
- Solar production (P_PV): Power being generated by solar panels
- Load (P_Load): Power being consumed by the house
- Grid (P_Grid): Power being imported/exported from/to the grid
- Battery (P_Akku): Power being stored/used from battery (if available)
"""

import requests
from typing import Dict, Optional

class FroniusClient:
    def __init__(self, host: str, port: int = 80):
        """Initialize the Fronius API client.
        
        Args:
            host: The IP address or hostname of the Fronius inverter
            port: The port number (default: 80)
        """
        # Construct the base URL for API requests
        self.base_url = f"http://{host}:{port}"
        
    def get_power_data(self) -> Dict:
        """Fetch current power data from the Fronius inverter.
        
        This method calls the GetPowerFlowRealtimeData.fcgi endpoint to get
        real-time power flow data from the inverter.
        
        Returns:
            Dict containing:
                - P_PV: Solar production in watts
                - P_Load: House consumption in watts
                - P_Grid: Grid power flow in watts (positive = export, negative = import)
                - P_Akku: Battery power flow in watts (if available)
                - E_Day: Energy produced today in watt-hours
                - E_Total: Total energy produced in watt-hours
                - E_Year: Energy produced this year in watt-hours
                - rel_Autonomy: Percentage of energy autonomy
                - rel_SelfConsumption: Percentage of self-consumption
        """
        # Endpoint for power flow data (v1 API)
        url = f"{self.base_url}/solar_api/v1/GetPowerFlowRealtimeData.fcgi"
        
        try:
            # Make HTTP GET request to the inverter
            response = requests.get(url)
            response.raise_for_status()  # Raise exception for bad status codes
            data = response.json()
            
            # Extract relevant power data from the nested JSON response
            site_data = data.get('Body', {}).get('Data', {}).get('Site', {})
            power_data = {
                'P_PV': site_data.get('P_PV', 0),
                'P_Load': site_data.get('P_Load', 0),
                'P_Grid': site_data.get('P_Grid', 0),
                'P_Akku': site_data.get('P_Akku', 0),
                'E_Day': site_data.get('E_Day', 0),
                'E_Total': site_data.get('E_Total', 0),
                'E_Year': site_data.get('E_Year', 0),
                'rel_Autonomy': site_data.get('rel_Autonomy', 0),
                'rel_SelfConsumption': site_data.get('rel_SelfConsumption', 0)
            }
            
            return power_data
            
        except requests.RequestException as e:
            # Handle any connection or API errors
            print(f"Error fetching power data: {e}")
            # Return zero values if we can't get real data
            return {
                'P_PV': 0,
                'P_Load': 0,
                'P_Grid': 0,
                'P_Akku': 0,
                'E_Day': 0,
                'E_Total': 0,
                'E_Year': 0,
                'rel_Autonomy': 0,
                'rel_SelfConsumption': 0
            }
    
    def is_available(self) -> bool:
        """Check if the Fronius inverter is available and responding.
        
        Returns:
            bool: True if the inverter responds, False otherwise
        """
        try:
            url = f"{self.base_url}/solar_api/v1/GetPowerFlowRealtimeData.fcgi"
            response = requests.get(url, timeout=5)
            response.raise_for_status()
            return True
        except Exception:
            return False 